name: Build Executables

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write  # needed to create releases and upload assets

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build
        run: pyinstaller --onefile main.py

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/main
            dist/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}